'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManagerLoanApprove

    '''<summary>
    '''divalert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divalert As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''msgalert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgalert As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblloantype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblloantype As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLoanRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoanRefNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGradeLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGradeLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblstatustemp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstatustemp2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtapproverlevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtapproverlevel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pagetitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagetitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblloandate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblloandate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblamount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblamount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApprover As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblFinalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalStatus As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblguarantor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblguarantor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblguarantorname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblguarantorname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblGuarantorStatus1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGuarantorStatus1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGuarantorStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGuarantorStatus As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblgcomment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblgcomment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblguarantorcomment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblguarantorcomment As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblrepaymentstartdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrepaymentstartdate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblRepayAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRepayAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblTenor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTenor As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesc As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboApproval As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComment As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblFinanceApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinanceApproval As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStatus As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
