'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EmployeeData
    
    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''divalert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divalert As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''msgalert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgalert As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtIDContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDContact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtIDEmergency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDEmergency As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btpersonal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btpersonal As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btemercontact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btemercontact As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btdependants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btdependants As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btqualification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btqualification As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btcareer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btcareer As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''pagetitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagetitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''imgphoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgphoto As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''imgUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUpload As Global.System.Web.UI.HtmlControls.HtmlInputFile
    
    '''<summary>
    '''chkPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPay As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''aempid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aempid As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btgenerateempid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btgenerateempid As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''alastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alastname As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''afirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents afirstname As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''amiddlename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amiddlename As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''drpgender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpgender As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''adateofbirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adateofbirth As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''drpmaritalstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpmaritalstatus As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''drpnationality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpnationality As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''drpcountryofbirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpcountryofbirth As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''astateorigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents astateorigin As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''abirthplace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents abirthplace As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''aidtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aidtype As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''aidnumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aidnumber As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''aidissuer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aidissuer As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''aidexpirydate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aidexpirydate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''adateresume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adateresume As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''divconfirmexpected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divconfirmexpected As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''adateexpectconfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adateexpectconfirm As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''divconfirmdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divconfirmdate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''adateconfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adateconfirm As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''divterminatedate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divterminatedate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''aterminatedate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aterminatedate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''divlogcreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divlogcreate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chklogcreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chklogcreate As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''aphonenumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aphonenumber As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''aworkphonenumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aworkphonenumber As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''aemailaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aemailaddress As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''aworkemailaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aworkemailaddress As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''aaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aaddress As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''aaddresscity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aaddresscity As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''drpaddresscountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpaddresscountry As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divlogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divlogin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ausername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ausername As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''apassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apassword As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''cbouserrole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbouserrole As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''cbouserstat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbouserstat As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''cbouseraccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbouseraccess As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''UpdatePanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel6 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''cbouseraccesslevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbouseraccesslevel As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''auseremail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents auseremail As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''chksuperadmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chksuperadmin As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''chkhradmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkhradmin As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''chkfinadmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkfinadmin As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''btsavepersonal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btsavepersonal As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnback As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''Emergency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Emergency As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''collapse_acc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collapse_acc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divbtnapprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divbtnapprove As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkApprove As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCancel As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''B1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tempaemername1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempaemername1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tempaemercontactnumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempaemercontactnumber1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''drptemprelation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drptemprelation1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tempaemeraddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempaemeraddress1 As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''tempaemername2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempaemername2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tempaemercontactnumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempaemercontactnumber2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''drptemprelation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drptemprelation2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''tempaemeraddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempaemeraddress2 As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''aemername1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aemername1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''aemercontactnumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aemercontactnumber1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''drpemerrelation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpemerrelation1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''aemeraddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aemeraddress1 As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''aemername2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aemername2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''aemercontactnumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aemercontactnumber2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''drprelation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drprelation2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''aemeraddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aemeraddress2 As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''arefname1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arefname1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''arefphonenumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arefphonenumber1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''arefemailaddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arefemailaddress1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''arefyrsknown1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arefyrsknown1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''drprefconfirmed1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drprefconfirmed1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''areforganisation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areforganisation1 As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''arefname2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arefname2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''arefcontactnumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arefcontactnumber2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''arefemailaddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arefemailaddress2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''arefyears2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arefyears2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''drprefconfirmed2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drprefconfirmed2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''areforganisation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areforganisation2 As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''Dependants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dependants As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''btnsavedependants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsavedependants As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btndeletedependants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndeletedependants As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridVwHeaderChckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridVwHeaderChckbox As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''Qualifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Qualifications As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''btnaddeducatin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnaddeducatin As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btndeleteeducation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndeleteeducation As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridVwEducation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridVwEducation As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnaddcertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnaddcertificate As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btndeletecertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndeletecertificate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridVwCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridVwCertification As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnaddlanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnaddlanguage As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btndeletelanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndeletelanguage As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridVwLang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridVwLang As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnaddskills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnaddskills As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btndeleteskills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndeleteskills As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridVwSkills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridVwSkills As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Button3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button3 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''WorkHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WorkHistory As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''btnaddcareer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnaddcareer As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btndeletecareer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndeletecareer As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridVwWorkHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridVwWorkHistory As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Button4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button4 As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
