'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PayrollPeriodData

    '''<summary>
    '''divalert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divalert As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''msgalert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgalert As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpayotionid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpayotionid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStart As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents content As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pagetitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagetitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cboapprovalstat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboapprovalstat As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriod As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblNetPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNetPay As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtcomment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcomment As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblapprovedby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblapprovedby As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lbldateapproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldateapproved As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblcreatedby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcreatedby As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblcreatedon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcreatedon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblPayrollStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayrollStat As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cbopayrollstat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbopayrollstat As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStat As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
